### ISSUE TITLE
Update sbatch_master to output --ntasks instead of --cpus_per_task

### ISSUE THREAD

**Issue by sgoodreau** [EpiModel/EpiModelHPC#43] opened 2023-11-20 23:40 UTC
this was triggered by an update to the slurm scheduler on mox:

`*NOTE: Beginning with 22.05, srun will not inherit the --cpus-per-task value requested by salloc or sbatch. It must be requested again with the call to srun or set with the SRUN_CPUS_PER_TASK environment variable if desired for the task(s).*`

Matt the UW Hyak manager explored and discovered that this change to our master.sh files would get it working again. 

If I understand Adrien's email correctly, he will also make some sort of parallel change in `slurmworkflow`

**Comment by AdrienLeGuillou** [comment] 2023-11-22 08:45
I will get to that soon. I'll recap what I understand of the issue here for when I get to it. 

I do not think `slurmworkflow` will need an update. It's bare bone design makes it more resilient to these changes. The scenarios step_templates on `EpiModelHPC` are still working fine on all HPCs so no issues here for now as well.

Next step: 

Check if the issue is in the allocation of resources by `slurm` (`ntasks` vs `cpus-per-task`). That would be weird as MOX always allocate full nodes.

Check if the issue is on the discovery of the CPUs available by R. 

Reminder: the calls produced only 1 sim rep per array job instead of 10. Even with a wrong number of CPU, the 10 should be run sequentially. (hint: `nsims` vs `ncores` on `netsim`)


```
# master.9999.sh
sbatch -p ckpt -A csde-ckpt --array=1-3 --nodes=1 --cpus-per-task=10 --time=10:00:00 --mem=100G --job-name=s9999 --export=ALL,SIMNO=9999,NJOBS=3,NSIMS=30 runsim.9999.sh
```

```
# runsim.9999.sh

#!/bin/bash

#SBATCH -o ./out/%x_%a.out

source ~/loadR.sh
Rscript sim.9999.R
```

```r
# sim.9999.R
library("methods")
library("EpiModelHIV")
library("EpiModelHPC")

pull_env_vars()

# Params
epistats_list <- readRDS("est/epistats_list.rds")
epistats <- epistats_list[[1]]
netstats_list <- readRDS("est/netstats_list.rds")
netstats <- netstats_list[[1]]

# Epidemic model

time.unit <- 7
method <- 1

param <- param_msm(
  netstats = netstats,
  epistats = epistats,
  pr.postprep.condom.nonrebounder = 0.25,
  dur.postprep.condom.nonrebounder = 52,
  cai.cutoff.times = (600+(1:2))*52
)

init <- init_msm()

control <- control_msm(simno = fsimno,
                       nsteps = (600*52) + 5,
                       nsims = ncores,
                       ncores = ncores,
                       start = (600*52) + 1,
                       initialize.FUN = reinit_msm,
                       verbose = TRUE,
                       tergmLite = TRUE)

netsim_hpc("data/sim.n1206_bcb.rda", param, init, control, compress=FALSE,
           verbose = TRUE, save.min=FALSE, save.max=TRUE)
```

**Comment by AdrienLeGuillou** [comment] 2023-11-23 11:18
It seems that it is not an issue but a case of breaking changes between v2.1.0 and v2.2.0 
Closing unless new info arise

**Closed by AdrienLeGuillou** 2023-11-23 11:18 UTC
